apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlops-flask-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mlops-app
  template:
    metadata:
      labels:
        app: mlops-app
    spec:
      containers:
      - name: mlops-flask-container
        image: prakasarul222/mlops:tag
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
# service type loadbalancer       
---
apiVersion: v1
kind: Service
metadata:
  name: mlops-flask-svc
spec:
  selector:
    app: mlops-app
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: LoadBalancer
